<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: plugin.lang.php 30542 2012-06-01 08:03:33Z zhengqingpeng $
 */

if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}


$devlang = array
(
	//note ²å¼þÏà¹Ø	ÇëÒÔ plugins_ ¿ªÍ·
	'author' => '×÷Õß',
	'add_new' => 'ÐÂÔö',
	//note ÓÃ»§×éÏà¹Ø	ÇëÒÔ usergroups_ ¿ªÍ·
	'usergroups' => 'ÓÃ»§×é',
	'usergroups_system_0' => 'ÆÕÍ¨ÓÃ»§',
	'usergroups_system_1' => '¹ÜÀíÔ±',
	'usergroups_system_2' => '³¬¼¶°æÖ÷',
	'usergroups_system_3' => '°æÖ÷',
	'usergroups_system_4' => '½ûÖ¹·¢ÑÔ',
	'usergroups_system_5' => '½ûÖ¹·ÃÎÊ',
	'usergroups_system_6' => 'ÓÃ»§IP±»½ûÖ¹',
	'usergroups_system_7' => 'ÓÎ¿Í',
	'usergroups_system_8' => 'µÈ´ýÑéÖ¤',
	'plugins' => '²å¼þÅäÖÃ',
	'plugins_home' => '½éÉÜ',
	'plugins_editlink' => 'Éè¼Æ',
	'plugins_validator' => '¼ì²é¸üÐÂ',
	'plugins_list' => '²å¼þÁÐ±í',
	'plugins_system' => 'ÏµÍ³²å¼þ',
	'plugins_install' => '°²×°ÐÂ²å¼þ',
	'plugins_newcomment' => 'ÒÔÏÂÎª²å¼þÄ¿Â¼ source/plugin/ ÏÂÎ´°²×°µÄ²å¼þ',
	'plugins_menu' => '²å¼þ',
	'plugins_name' => '²å¼þÃû³Æ',
	'plugins_unavailable' => '±¾²å¼þÎ´±»ÆôÓÃ',
	'plugins_empty' => '¿Õ',
	'plugins_directory' => '²å¼þÄ¿Â¼',
	'plugins_identifier' => 'Î¨Ò»±êÊ¶·û',
	'plugins_vars_title' => 'ÅäÖÃÃû³Æ(±ØÌî)',
	'plugins_vars_variable' => 'ÅäÖÃ±äÁ¿Ãû(±ØÌî)',
	'plugins_vars_type' => 'ÅäÖÃÀàÐÍ',
	'plugins_add' => 'Éè¼ÆÐÂ²å¼þ',
	'plugins_add_tips' => '<li><b>±¾¹¦ÄÜ½ö¹©²å¼þ¿ª·¢ÕßÊ¹ÓÃ¡£</b></li><li>²å¼þ¿ª·¢ÈËÔ±ÔÚÊ¹ÓÃ±¾¹¦ÄÜÇ°ÇëÎñ±Ø×ÐÏ¸ÔÄ¶Á¡¶<a href="http://dev.discuz.org/wiki" target="_blank">Discuz! ¼¼ÊõÎÄ¿â</a>¡·ÖÐµÄÄÚÈÝ¡£</li><li>¾¯¸æ: ²»ÕýÈ·µÄ²å¼þÉè¼Æ»ò°²×°¿ÉÄÜÎ£¼°µ½Õû¸öÕ¾µãµÄÕý³£Ê¹ÓÃ¡£</li>',
	'plugins_import' => 'µ¼Èë²å¼þÊý¾Ý',
	'plugins_import_ignore_version' => 'ÔÊÐíµ¼ÈëÀÏ°æ±¾ Discuz! µÄ²å¼þ(Ò×²úÉú´íÎó!!)',
	'plugins_update_to' => '¸üÐÂµ½ ',
	'plugins_config' => '²ÎÊýÉèÖÃ',
	'plugins_config_module' => 'Ä£¿é',
	'plugins_config_vars' => '±äÁ¿',
	'plugins_config_install' => '°²×°',
	'plugins_config_uninstall' => 'Ð¶ÔØ',
	'plugins_config_upgrade' => '¸üÐÂ',
	'plugins_config_delete' => 'Ð¶ÔØ',
	'plugins_config_upgrade_other' => 'ÄúÈ·¶¨Òª°Ñ {pluginname} {version} ²å¼þ¸üÐÂµ½ÒÔÏÂ°æ±¾Âð£¿',
	'plugins_config_uninstallplugin' => 'Ð¶ÔØ´Ë²å¼þ',
	'plugins_edit' => 'Éè¼Æ²å¼þ',
	'plugins_edit_available' => ' (²å¼þÒÑÆôÓÃ)',
	'plugins_edit_tips' => '<li><b>±¾¹¦ÄÜ½ö¹©²å¼þ¿ª·¢ÕßÊ¹ÓÃ£¬Èç¹ûÄúÖ»ÊÇ°²×°»òÊ¹ÓÃ±¾²å¼þ£¬ÇÐÎðÐÞ¸Ä±¾ÉèÖÃ¡£</b></li><li>²å¼þ¿ª·¢ÈËÔ±ÔÚÊ¹ÓÃ±¾¹¦ÄÜÇ°ÇëÎñ±Ø×ÐÏ¸ÔÄ¶Á¡¶<a href="http://dev.discuz.org/wiki" target="_blank">Discuz! ¼¼ÊõÎÄ¿â</a>¡·ÖÐµÄÄÚÈÝ¡£</li><li>¾¯¸æ: ²»ÕýÈ·µÄ²å¼þÉè¼Æ»ò°²×°¿ÉÄÜÎ£¼°µ½Õû¸öÕ¾µãµÄÕý³£Ê¹ÓÃ¡£</li><li>°ÑÉè¼ÆÍêµÄ²å¼þ·¢²¼µ½<a href="http://addon.discuz.com" target="_blank">¡°Discuz! Ó¦ÓÃÖÐÐÄ¡±</a>·ÖÏí¸ø¹ã´óÕ¾³¤¡£</li>',
	'plugins_edit_name' => '²å¼þÃû³Æ(name)',
	'plugins_edit_name_comment' => '´Ë²å¼þµÄÃû³Æ£¬ÖÐÓ¢ÎÄ¾ù¿É£¬×î¶à 40 ¸ö×Ö½Ú',
	'plugins_edit_version' => '²å¼þ°æ±¾ºÅ(version)',
	'plugins_edit_version_comment' => '´Ë²å¼þµÄ°æ±¾£¬ÖÐÓ¢ÎÄ¾ù¿É£¬×î¶à 20 ¸ö×Ö½Ú¡£°æ±¾ºÅ¸ßÓÚ¾É°æ±¾ºÅÊ±£¬°²×°¸øÓÃ»§Ê±½«»áÌáÊ¾¸üÐÂ',
	'plugins_edit_copyright' => '°æÈ¨ÐÅÏ¢(copyright)',
	'plugins_edit_copyright_comment' => 'ÉèÖÃ²å¼þµÄ°æÈ¨ÐÅÏ¢£¬×î¶à 100 ¸ö×Ö½Ú£¬Ò»µ©ÉèÖÃÎÞ·¨¸ü¸Ä',
	'plugins_edit_identifier' => 'Î¨Ò»±êÊ¶·û(identifier)',
	'plugins_edit_identifier_comment' => '²å¼þµÄÎ¨Ò»Ó¢ÎÄ±êÊ¶£¬²»ÄÜ¹»ÓëÏÖÓÐ²å¼þ±êÊ¶ÖØ¸´¡£¿ÉÊ¹ÓÃ×ÖÄ¸¡¢Êý×Ö¡¢ÏÂ»®ÏßÃüÃû£¬²»ÄÜ°üº¬ÆäËû·ûºÅ»òÌØÊâ×Ö·û£¬×î´ó 40 ¸ö×Ö½Ú',
	'plugins_edit_adminid' => 'ºóÌ¨È¨ÏÞµÈ¼¶(adminid)',
	'plugins_edit_adminid_comment' => 'Ê¹ÓÃ¹ÜÀíÖÐÐÄÖÐ²å¼þ½Ó¿Ú×Ô´øµÄ²å¼þ²ÎÊýÉèÖÃ³ÌÐòËùÐèµÄ×îµÍÈ¨ÏÞµÈ¼¶ÒªÇó¡£×¢Òâ: ²å¼þµÄºóÌ¨Ä£¿éÓµÓÐ×Ô¼ºµÄÈ¨ÏÞÉèÖÃ£¬Òò´Ë²»ÊÜ´ËÏÞÖÆ',
	'plugins_edit_directory' => '²å¼þÄ¿Â¼(directory)',
	'plugins_edit_directory_comment' => '²å¼þ³ÌÐò(°üÀ¨Ç°Ì¨ºÍºóÌ¨)Ïà¶ÔÓÚ source/plugin/ µÄÏà¶ÔÂ·¾¶£¬±ØÐëÒÔ "/" ½áÎ²£¬·ñÔò»á²úÉú´íÎó¡£Èç¹û²»Ö¸¶¨±¾ÉèÖÃ£¬ÔòÄ¬ÈÏ²å¼þµÄÇ°ºóÌ¨³ÌÐò¾ù·ÅÖÃÓÚ source/plugin/ Àï¡£ ',
	'plugins_edit_description' => '²å¼þÃèÊö(description)',
	'plugins_edit_description_comment' => '²å¼þµÄ¼òµ¥ÃèÊö£¬×î¶à 100 ¸ö×Ö½Ú£¬¿ÉÑ¡Ìî',
	'plugins_edit_langexists' => '²å¼þÓïÑÔ°ü',
	'plugins_edit_langexists_comment' => 'Èç¹û²å¼þ´æÔÚÓïÑÔ°ü£¬ÇëÑ¡Ôñ¡°ÊÇ¡±',
	'plugins_edit_modules' => '²å¼þÄ£¿éºÍµ¼º½',
	'plugins_edit_modules_name' => '³ÌÐòÄ£¿é(±ØÌî)',
	'plugins_edit_modules_menu' => 'Á´½ÓÃû³Æ',
	'plugins_edit_modules_menu_url' => 'Á´½Ó URL',
	'plugins_edit_modules_navtitle' => 'µ¼º½ËµÃ÷',
	'plugins_edit_modules_navicon' => 'µ¼º½Í¼±ê',
	'plugins_edit_modules_navsubname' => '¸±µ¼º½Ãû³Æ',
	'plugins_edit_modules_navsuburl' => '¸±µ¼º½Á´½Ó',
	'plugins_edit_modules_type' => 'Ä£¿éÀàÐÍ',
	'plugins_edit_modules_type_1' => 'Ö÷µ¼º½ÏîÄ¿',
	'plugins_edit_modules_type_2' => '',
	'plugins_edit_modules_type_5' => 'Ö÷µ¼º½ÏîÄ¿ - ²å¼þ²Ëµ¥',
	'plugins_edit_modules_type_23' => 'µ×²¿µ¼º½ÏîÄ¿',
	'plugins_edit_modules_type_24' => '¼ÒÔ°µ¼º½ÏîÄ¿',
	'plugins_edit_modules_type_25' => '¿ì½Ýµ¼º½ÏîÄ¿',
	'plugins_edit_modules_type_6' => '',
	'plugins_edit_modules_type_7' => '¸öÈËÉèÖÃ',
	'plugins_edit_modules_type_8' => '',
	'plugins_edit_modules_type_9' => '',
	'plugins_edit_modules_type_10' => '',
	'plugins_edit_modules_type_3' => '¹ÜÀíÖÐÐÄ',
	'plugins_edit_modules_type_4' => 'È«¾Ö°üº¬',
	'plugins_edit_modules_type_11' => 'Ò³ÃæÇ¶Èë - ÆÕÍ¨°æ',
	'plugins_edit_modules_type_12' => 'ÌØÊâÖ÷Ìâ',
	'plugins_edit_modules_type_13' => 'ÆÕÍ¨½Å±¾',
	'plugins_edit_modules_type_14' => 'Õ¾µã°ïÖú',
	'plugins_edit_modules_type_15' => 'ÂÛÌ³¹ÜÀí - »ù±¾',
	'plugins_edit_modules_type_16' => 'ÂÛÌ³¹ÜÀí - ¹¤¾ß',
	'plugins_edit_modules_type_17' => '¸öÈËÉèÖÃ - ¸öÈË×ÊÁÏ',
	'plugins_edit_modules_type_19' => '¸öÈËÉèÖÃ - »ý·Ö',
	'plugins_edit_modules_type_18' => '',
	'plugins_edit_modules_type_21' => 'ÃÅ»§¹ÜÀí',
	'plugins_edit_modules_type_26' => 'ÎÒµÄÌû×Ó',
	'plugins_edit_modules_type_27' => '¶¥²¿µ¼º½ÏîÄ¿',
	'plugins_edit_modules_type_28' => 'Ò³ÃæÇ¶Èë - ÊÖ»ú°æ',
	'plugins_edit_modules_type_g1' => '³ÌÐòÁ´½Ó',
	'plugins_edit_modules_type_g2' => '³ÌÐò½Å±¾',
	'plugins_edit_modules_type_g3' => 'À©Õ¹ÏîÄ¿',
	'plugins_edit_modules_adminid' => 'Ê¹ÓÃµÈ¼¶',
	'plugins_edit_modules_include' => '°üº¬ÔËÐÐ',
	'plugins_edit_vars' => '²å¼þ±äÁ¿ÅäÖÃ',
	'plugins_edit_vars_title' => 'ÅäÖÃÃû³Æ',
	'plugins_edit_vars_title_comment' => 'ÖÐÓ¢ÎÄ¾ù¿É£¬ÓÃÓÚÏÔÊ¾ÔÚ²å¼þÅäÖÃµÄ²Ëµ¥ÖÐ£¬×î¶à 100 ¸ö×Ö½Ú¡£´Ë´¦Ö§³ÖÓïÑÔ¶¨Òå£¬ÀýÈç£ºlang_admincp.php ¶¨ÒåÁË \'myaction\'=>\'ÎÒµÄ²Ù×÷\' £¬Ôò´Ë´¦ÌîÐ´ myaction ¼´¿É£¬ÕâÑùÓÐÀûÓÚ¶àÓïÑÔ°æ±¾²å¼þµÄÖÆ×÷',
	'plugins_edit_vars_description' => 'ÅäÖÃËµÃ÷',
	'plugins_edit_vars_description_comment' => 'ÃèÊö´ËÏîÅäÖÃµÄÓÃÍ¾ºÍÈ¡Öµ·¶Î§£¬ÏêÏ¸µÄÃèÊöÓÐÀûÓÚ²å¼þÊ¹ÓÃÕßÁË½âÕâ¸öÉèÖÃµÄ×÷ÓÃ£¬×î¶à 255 ¸ö×Ö½Ú¡£´Ë´¦ºÍÅäÖÃÃû³ÆÀàËÆ£¬Ò²Ö§³ÖÓïÑÔ¶¨Òå',
	'plugins_edit_vars_type' => 'ÅäÖÃÀàÐÍ',
	'plugins_edit_vars_type_number' => 'Êý×Ö(number)',
	'plugins_edit_vars_type_text' => '×Ö´®(text)',
	'plugins_edit_vars_type_textarea' => 'ÎÄ±¾(textarea)',
	'plugins_edit_vars_type_radio' => '¿ª¹Ø(radio)',
	'plugins_edit_vars_type_select' => 'µ¥Ñ¡Ñ¡Ôñ(select)',
	'plugins_edit_vars_type_selects' => '¶àÏîÑ¡Ôñ(selects)',
	'plugins_edit_vars_type_color' => 'ÑÕÉ«(color)',
	'plugins_edit_vars_type_date' => 'ÈÕÆÚ(date)',
	'plugins_edit_vars_type_datetime' => 'ÈÕÆÚ/Ê±¼ä(datetime)',
	'plugins_edit_vars_type_forum' => '°æ¿éµ¥Ñ¡(forum)',
	'plugins_edit_vars_type_forums' => '°æ¿é¶àÑ¡(forums)',
	'plugins_edit_vars_type_group' => 'ÓÃ»§×éµ¥Ñ¡(group)',
	'plugins_edit_vars_type_groups' => 'ÓÃ»§×é¶àÑ¡(groups)',
	'plugins_edit_vars_type_extcredit' => 'À©Õ¹»ý·Ö(extcredit)',
	'plugins_edit_vars_type_forum_text' => '°æ¿é/×Ö´®(forum_text)',
	'plugins_edit_vars_type_forum_textarea' => '°æ¿é/ÎÄ±¾(forum_textarea)',
	'plugins_edit_vars_type_forum_radio' => '°æ¿é/¿ª¹Ø(forum_radio)',
	'plugins_edit_vars_type_forum_select' => '°æ¿é/µ¥Ñ¡Ñ¡Ôñ(forum_select)',
	'plugins_edit_vars_type_group_text' => 'ÓÃ»§×é/×Ö´®(group_text)',
	'plugins_edit_vars_type_group_textarea' => 'ÓÃ»§×é/ÎÄ±¾(group_textarea)',
	'plugins_edit_vars_type_group_radio' => 'ÓÃ»§×é/¿ª¹Ø(group_radio)',
	'plugins_edit_vars_type_group_select' => 'ÓÃ»§×é/µ¥Ñ¡Ñ¡Ôñ(group_select)',
	'plugins_edit_vars_multiselect_comment' => '°´×¡ CTRL ¶àÑ¡',
	'plugins_edit_vars_type_comment' => 'ÉèÖÃ´ËÅäÖÃµÄÊý¾ÝÀàÐÍ£¬ÓÃÓÚ³ÌÐòÖÐ¼ì²éºÍ¹ýÂËÏàÓ¦ÅäÖÃÖµ',
	'plugins_edit_vars_variable' => 'ÅäÖÃ±äÁ¿Ãû',
	'plugins_edit_vars_variable_comment' => 'ÉèÖÃÅäÖÃÏîÄ¿µÄ±äÁ¿Ãû£¬ÓÃÓÚ²å¼þ³ÌÐòÖÐµ÷ÓÃ£¬¿É°üº¬Ó¢ÎÄ¡¢Êý×ÖºÍÏÂ»®Ïß£¬ÔÚÍ¬Ò»¸ö²å¼þÖÐÐèÒª±£³Ö±äÁ¿ÃûµÄÎ¨Ò»ÐÔ£¬×î¶à 40 ¸ö×Ö½Ú',
	'plugins_edit_vars_extra' => 'À©³äÉèÖÃ',
	'plugins_edit_vars_extra_comment' => 'Ö»ÔÚÅäÖÃÀàÐÍÎª¡°Ñ¡Ôñ(select)¡±Ê±ÓÐÐ§£¬ÓÃÓÚÉè¶¨Ñ¡ÏîÖµ¡£µÈºÅÇ°ÃæÎªÑ¡ÏîË÷Òý(½¨ÒéÓÃÊý×Ö)£¬ºóÃæÎªÄÚÈÝ£¬ÀýÈç: <br /><i>1 = ¹âµçÊó±ê<br />2 = »úÐµÊó±ê<br />3 = Ã»ÓÐÊó±ê</i><br />×¢Òâ: Ñ¡ÏîÈ·¶¨ºóÇëÎðÐÞ¸ÄË÷ÒýºÍÄÚÈÝµÄ¶ÔÓ¦¹ØÏµ£¬µ«ÈÔ¿ÉÒÔÐÂÔöÑ¡Ïî¡£ÈçÐèµ÷»»ÏÔÊ¾Ë³Ðò£¬¿ÉÒÔÍ¨¹ýÒÆ¶¯ÕûÐÐµÄÉÏÏÂÎ»ÖÃÀ´ÊµÏÖ',
	'plugins_import_default' => 'Ä¬ÈÏ',
	'plugins_import_installtype_1' => '²å¼þ',
	'plugins_import_installtype_2' => 'Ìá¹©ÁËÒÔÏÂ',
	'plugins_import_installtype_3' => 'ÖÖ°²×°·½Ê½£¬ÇëÑ¡Ôñ',
	'plugins_import_license' => 'ÊÚÈ¨Ð­Òé',
	'plugins_import_agree' => 'ÎÒÍ¬Òâ',
	'plugins_import_pass' => 'ÎÒ²»Í¬Òâ',
	'plugins_conflict_view' => '²é¿´Ï¸½Ú',
	'plugins_conflict_info' => 'ÁªÏµ×÷Õß',
	'plugins_module_sample' => '<span title="ÏÂÔØÄ£¿éÄ£°åÎÄ¼þ">[&darr;]</span>',
	'plugins_find_newversion' => '·¢ÏÖÐÂ°æ',
	'plugins_online_update' => 'µã»÷ÔÚÏß°²×°ÐÂ°æ',
	'plugins_list_available' => 'ÒÑÆôÓÃµÄ²å¼þ',
	'plugins_list_unavailable' => 'Î´ÆôÓÃµÄ²å¼þ',
	'plugins_list_new' => 'Î´°²×°µÄ²å¼þ',
	'plugins_enable_succeed' => '²å¼þÒÑÆôÓÃ',
	'plugin_not_found' => '²å¼þÎ´ÕÒµ½',
	'plugins_install_succeed' => '²å¼þ³É¹¦°²×°£¡<br />ÎªÁËÕý³£Ê¹ÓÃ´Ë²å¼þ£¬Äú¿ÉÄÜ»¹ÐèÒªÉÏ´«»òÐÞ¸ÄÏàÓ¦µÄÎÄ¼þ»òÄ£°å£¬ÏêÇéÇë²é¿´±¾²å¼þµÄ°²×°ËµÃ÷<br /><br /><a href="http://addon.discuz.com?view=plugins">µã»÷ÕâÀï·µ»ØÓ¦ÓÃÖÐÐÄ</a><br />',
	'plugin_file_error' => '²å¼þÎÄ¼þÈ±Ê§',
	'plugins_edit_identifier_invalid' => 'ÄúÊäÈëµÄÎ¨Ò»±êÊ¶·û²»ºÏ·¨»òÓëÏÖÓÐ²å¼þÖØ¸´',
	'plugins_upgrade_succeed' => '²å¼þ³É¹¦¸üÐÂµ½ {toversion}<br /><br /><a href="http://addon.discuz.com?view=plugins">µã»÷ÕâÀï·µ»ØÓ¦ÓÃÖÐÐÄ</a><br />',
	'plugins_edit_name_invalid' => 'ÄúÃ»ÓÐÊäÈë²å¼þÃû³Æ',
	'plugins_edit_succeed' => '²å¼þÅäÖÃ¸üÐÂ³É¹¦ ',
	'plugins_delete_succeed' => '²å¼þ³É¹¦Ð¶ÔØ£¡<br />ÎªÁËÕý³£Ð¶ÔØ´Ë²å¼þ£¬Äú¿ÉÄÜ»¹ÐèÒªÉ¾³ý»òÐÞ¸ÄÏàÓ¦µÄÎÄ¼þ»òÄ£°å£¬ÏêÇéÇë²é¿´±¾²å¼þµÄ°²×°ËµÃ÷',
	'plugins_conflict' => '²å¼þÒÑÆôÓÃ</h4><br />ÓÑÇéÌáÊ¾£ºÄú¸ÕÆôÓÃµÄ²å¼þÓëÄ³Ð©²å¼þ´æÔÚ¹²ÓÃµÄÇ¶Èëµã¡£ËäÈ»¹²ÓÃÇ¶ÈëµãÊôÓÚÕý³£Çé¿ö£¬µ«ÊÇÈç¹ûÄúÓöµ½²å¼þÔËÐÐ²»Õý³£µÄÇé¿öÇë¼°Ê±ÁªÏµ²å¼þ×÷Õß¡£<a href="javascript:;" onclick="display(\'conflict\')">[µã»÷²é¿´]</a><br /><div id="conflict" style="display:none"><br />{plugins}<br /></div><br />',
	'plugins_disable_succeed' => '²å¼þÒÑ¹Ø±Õ',
	'plugins_import_var_invalid' => '²å¼þµÄÇ¶ÈëµãÃû³Æ²»ºÏ·¨£¬ÎÞ·¨µ¼Èë',
	'plugins_import_identifier_duplicated' => 'ÄúÒªµ¼ÈëµÄ²å¼þ({plugin_name})ÒÑ¾­°²×°',
	'plugins_import_version_invalid_confirm' => '±¾²å¼þÊÊÓÃÓÚ Discuz! {cur_version} Óëµ±Ç°°æ±¾({set_version})²»Ò»ÖÂ£¬ÄúÈ·¶¨Òª°²×°Âð£¿<br />Èç¹û±¾²å¼þµÄ°²×°ËµÃ÷ÖÐ²»°üº¬ÐÞ¸ÄÎÄ¼þµÄÄÚÈÝÔòËµÃ÷´Ë²å¼þÎªÂÌÉ«²å¼þ£¬Äú¿É·ÅÐÄ°²×°',
	'plugins_import_version_invalid' => '±¾²å¼þÊÊÓÃÓÚ Discuz! {cur_version} Óëµ±Ç°°æ±¾({set_version})²»Ò»ÖÂ',
	'plugins_import_succeed' => '²å¼þÊý¾Ýµ¼Èë³É¹¦£¡<br />ÎªÁËÕý³£Ê¹ÓÃ´Ë²å¼þ£¬Äú¿ÉÄÜ»¹ÐèÒªÉÏ´«»òÐÞ¸ÄÏàÓ¦µÄÎÄ¼þ»òÄ£°å£¬ÏêÇéÇë²é¿´±¾²å¼þµÄ°²×°ËµÃ÷',
	'plugins_config_upgrade_confirm' => 'ÄúÈ·¶¨Òª°Ñ {pluginname} {version} ²å¼þ¸üÐÂµ½ {toversion} Âð£¿',
	'plugins_config_upgrade_missed' => '´Ë²å¼þÒÑ¸üÐÂµ½×îÐÂ°æ±¾<br /><br /><a href="http://addon.discuz.com?view=plugins">µã»÷ÕâÀï·µ»ØÓ¦ÓÃÖÐÐÄ</a><br />',
	'plugins_upgrade_var_invalid' => '²å¼þµÄÇ¶ÈëµãÃû³Æ²»ºÏ·¨£¬ÎÞ·¨¸üÐÂ',
	'plugins_setting_succeed' => '²å¼þ²ÎÊýÉèÖÃ¸üÐÂ³É¹¦ ',
	'plugins_setting_module_nonexistence' => 'Ö¸¶¨µÄ²å¼þ¹ÜÀíÄ£¿éÎÄ¼þ({modfile})²»´æÔÚ»ò´æÔÚÓï·¨´íÎó£¬Çë¼ì²éÊÇ·ñÒÑ½«²å¼þÍêÕûÉÏ´«',
	'plugins_add_succeed' => '²å¼þÒÑ³É¹¦Ìí¼Ó£¬Çë¼ÌÐø½øÐÐÏêÏ¸ÉèÖÃ',
	'plugins_nonexistence' => 'Äú¼´½«½øÐÐµÄ²Ù×÷£ºÉè¼Æ²å¼þ¡£ÇëÏÈÑ¡Ôñ²å¼þ£º',
	'plugin_donot_edit' => '²»ÔÊÐí±à¼­',
	'plugins_edit_directory_invalid' => 'ÄúÊäÈëµÄ²å¼þÄ¿Â¼²»ºÏ·¨»òÃ»ÓÐÊ¹ÓÃ "/" ½áÎ²',
	'plugins_edit_language_invalid' => '²å¼þÓïÑÔ°üÎÄ¼þ({langfile})²»´æÔÚ',
	'plugins_edit_modules_name_invalid' => 'ÄúÊäÈëµÄ³ÌÐòÄ£¿éÃû³Æ²»ºÏ·¨',
	'plugins_edit_modules_duplicated' => 'ÄúÊäÈëµÄ³ÌÐòÄ£¿éÃû³ÆÓëÏÖÓÐÄ£¿éÖØ¸´',
	'plugins_edit_var_invalid' => 'ÄúÊäÈëµÄÅäÖÃ±äÁ¿Ãû²»ºÏ·¨»òÖØ¸´',
	'plugins_delete_error' => 'Äú²»ÄÜÐ¶ÔØÏµÍ³²å¼þ¡£',
	'plugins_delete_confirm' => 'ÄúÈ·¶¨ÒªÐ¶ÔØ {pluginname} {toversion} ²å¼þÂð£¿<br /><br />ÇëÑ¡ÔñÄúÐ¶ÔØ¸ÃÓ¦ÓÃµÄÔ­Òò£¬ÒÔ±ãÎÒÃÇÒÔºóÎªÄúÌá¹©¸üºÃµÄÓ¦ÓÃ£º<br /><br /><label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="1" />¹¦ÄÜ²»Âú×ãÐèÇó</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="2" />½çÃæ²»ÃÀ¹Û</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="3" />Ð§ÂÊÎÊÌâÔËÐÐËÙ¶ÈÂý</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="4" />·¢ÏÖÁË¸üºÃµÄÓ¦ÓÃ</label><label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="5" />´¿ÊÔÓÃÏÖÔÚÐ¶ÔØ</label>',
	'styles_delete_confirm' => 'ÄúÈ·¶¨ÒªÐ¶ÔØÕâÐ©·ç¸ñÂð£¿<br /><br />ÇëÑ¡ÔñÄúÐ¶ÔØ¸ÃÓ¦ÓÃµÄÔ­Òò£¬ÒÔ±ãÎÒÃÇÒÔºóÎªÄúÌá¹©¸üºÃµÄÓ¦ÓÃ£º<br /><br /><label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="1" />¹¦ÄÜ²»Âú×ãÐèÇó</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="2" />½çÃæ²»ÃÀ¹Û</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="3" />Ð§ÂÊÎÊÌâÔËÐÐËÙ¶ÈÂý</label> <label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="4" />·¢ÏÖÁË¸üºÃµÄÓ¦ÓÃ</label><label><input name="uninstallreason[]" class="checkbox" type="checkbox" value="5" />´¿ÊÔÓÃÏÖÔÚÐ¶ÔØ</label>',
	'pluginvar_not_found' => '²å¼þ±äÁ¿Î´ÕÒµ½',
	'plugins_edit_var_title_invalid' => 'ÄúÃ»ÓÐÊäÈëÅäÖÃÃû³Æ',
	'plugins_edit_vars_succeed' => '²å¼þ±äÁ¿ÅäÖÃ¸üÐÂ³É¹¦ ',
	'plugins_edit_vars_invalid' => '²å¼þÅäÖÃ±äÁ¿Ãû²»ºÏ·¨»òÕßÒÑ±»Õ¼ÓÃ',
	'plugins_validator_noupdate' => 'Ã»ÓÐ¼ì²âµ½ÐÂ°æ±¾²å¼þ',
	'plugins_script_magic' => 'µÀ¾ß½Å±¾',
	'plugins_script_cron' => '¼Æ»®ÈÎÎñ½Å±¾',
	'plugins_script_adv' => '¹ã¸æ½Å±¾',
	'plugins_script_task' => 'Õ¾µãÈÎÎñ½Å±¾',
	'plugins_script_secqaa' => 'ÑéÖ¤ÎÊ´ð½Å±¾',
	'plugins_script_seccode' => 'ÑéÖ¤Âë½Å±¾',
	'plugins_script_navigation' => 'µ¼º½À¸Ä¿Ç¶Èë½Å±¾',
	'plugins_script_repeat' => 'ÎÄ¼þÃû³ÆÖØ¸´',
	'plugins_script_add' => 'Ìí¼Ó',
	'plugins_script_delete' => 'É¾³ý',
	);
?>